# Generated by Django 5.0.1 on 2024-01-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="pressure",
            field=models.FloatField(blank=True, null=True, verbose_name="Атмосферное давление, мм рт.ст."),
        ),
        migrations.AddField(
            model_name="city",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True, verbose_name="Скорость ветра, м/с"),
        ),
        migrations.AlterField(
            model_name="city",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="Температура, С"),
        ),
    ]
